version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - haines
    groups:
      aws:
        patterns:
          - aws*
      minitest:
        patterns:
          - minitest*
      rubocop:
        patterns:
          - rubocop*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - haines
