require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/bundle
    - bin/rake
    - bin/yard
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Exclude:
    - lib/pg/aws_rds_iam/auth_token_injector.rb
    - lib/pg/aws_rds_iam/connection_info.rb
    - lib/pg/aws_rds_iam/connection_info/**/*.rb
    - lib/pg/aws_rds_iam/connection.rb
    - test/**/*.rb

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
