name: Pull request

on:
  pull_request:

  pull_request_review:
    types:
      - submitted

permissions:
  actions: write

jobs:
  ci:
    name: Trigger CI

    if: |
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')
      ||
      (github.event.review.state == 'approved' && github.actor == 'haines')

    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI
        run: gh workflow run ci.yml --repo "${GITHUB_REPOSITORY}" --ref "${GITHUB_REF}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
